"""empty message

Revision ID: 180069164b3b
Revises: 875c794d6a5f
Create Date: 2022-02-11 16:45:38.698848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180069164b3b'
down_revision = '875c794d6a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cache_fused_entity', 'type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('file', 'git_commit', 'github_pullrequest', 'message', 'pep', 'person', name='entitytypeenum', native_enum=False),
               existing_nullable=False)
    op.add_column('cache_fused_entity', sa.Column('cached_names', sa.String(), nullable=True))
    op.create_index('idx_cache_fused_entity_cached_names', 'cache_fused_entity',
            ['cached_names'],
            #sa.text("(attrs -> 'cached_names')")],
            postgresql_using='gin',
            postgresql_ops={
                'cached_names': 'gin_trgm_ops',
            }, unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cache_fused_entity_cached_names', table_name='cache_fused_entity')
    op.drop_column('cache_fused_entity', 'cached_names')
    # ### end Alembic commands ###
