"""empty message

Revision ID: 4eebe3707185
Revises: 9149c9ca3367
Create Date: 2021-08-04 12:13:18.373442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eebe3707185'
down_revision = '9149c9ca3367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_fusion',
    sa.Column('id_other', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_lowest', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_lowest'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['id_other'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id_other')
    )
    op.create_index(op.f('ix_entity_fusion_id_lowest'), 'entity_fusion', ['id_lowest'], unique=False)
    op.drop_index('idx_observation_dst_by_timestamp', table_name='observation')
    op.create_index('idx_observation_dst_by_timestamp', 'observation', ['dst_id', 'time'], unique=False)
    op.drop_index('idx_observation_src_by_timestamp', table_name='observation')
    op.create_index('idx_observation_src_by_timestamp', 'observation', ['src_id', 'time'], unique=False)
    # ### end Alembic commands ###

    op.execute('CREATE EXTENSION pg_trgm')
    op.execute('CREATE EXTENSION fuzzystrmatch')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_observation_src_by_timestamp', table_name='observation')
    op.create_index('idx_observation_src_by_timestamp', 'observation', ['src_id', 'time', 'id'], unique=False)
    op.drop_index('idx_observation_dst_by_timestamp', table_name='observation')
    op.create_index('idx_observation_dst_by_timestamp', 'observation', ['dst_id', 'time', 'id'], unique=False)
    op.drop_index(op.f('ix_entity_fusion_id_lowest'), table_name='entity_fusion')
    op.drop_table('entity_fusion')
    # ### end Alembic commands ###
