"""empty message

Revision ID: da7682ae7b17
Revises: 4eebe3707185
Create Date: 2021-11-24 11:04:12.465468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da7682ae7b17'
down_revision = '4eebe3707185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attrs_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('super_type', sa.Enum('computed_attrs', 'entity', 'observation', name='supertypeenum', native_enum=False), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('computed_attrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('obj_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['attrs_base.id'], ),
    sa.ForeignKeyConstraint(['obj_id'], ['attrs_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computed_attrs_batch_id'), 'computed_attrs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_computed_attrs_obj_id'), 'computed_attrs', ['obj_id'], unique=False)
    op.create_foreign_key(None, 'entity', 'attrs_base', ['id'], ['id'])
    op.drop_column('entity', 'attrs')
    op.drop_constraint('observation_dst_id_fkey', 'observation', type_='foreignkey')
    op.drop_constraint('observation_src_id_fkey', 'observation', type_='foreignkey')
    op.create_foreign_key(None, 'observation', 'attrs_base', ['id'], ['id'])
    op.create_foreign_key(None, 'observation', 'entity', ['dst_id'], ['id'])
    op.create_foreign_key(None, 'observation', 'entity', ['src_id'], ['id'])
    op.drop_column('observation', 'attrs')
    op.drop_column('observation', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('observation', sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.create_foreign_key('observation_src_id_fkey', 'observation', 'entity', ['src_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('observation_dst_id_fkey', 'observation', 'entity', ['dst_id'], ['id'], ondelete='CASCADE')
    op.add_column('entity', sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_index(op.f('ix_computed_attrs_obj_id'), table_name='computed_attrs')
    op.drop_index(op.f('ix_computed_attrs_batch_id'), table_name='computed_attrs')
    op.drop_table('computed_attrs')
    op.drop_table('attrs_base')
    # ### end Alembic commands ###
